apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: colonies-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: {{ .Values.ColoniesServerHostname | quote }} 
    http:
      paths:
        - pathType: Prefix 
          path: /
          backend:
            service:
              name: colonies-service
              port: 
                number: 80
