apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ (.Values.StorageClassName) }}
  resources:
    requests:
      storage: {{ (.Values.DBStorage) }} 
